// Canonical Techno-Wizard gem reference data from Rifts Ultimate Edition.
export const RIFTS_GEMS = Object.freeze({
  "agate-fire": Object.freeze({ name: "Agate (fire)", pricePerCarat: 80 }),
  "agate-red-orange": Object.freeze({ name: "Agate (red-orange)", pricePerCarat: 60 }),
  "alexandrite": Object.freeze({ name: "Alexandrite", pricePerCarat: 3000 }),
  "amber": Object.freeze({ name: "Amber", pricePerCarat: 600 }),
  "amethyst": Object.freeze({ name: "Amethyst", pricePerCarat: 400 }),
  "androdite": Object.freeze({ name: "Androdite", pricePerCarat: 500 }),
  "aquamarine": Object.freeze({ name: "Aquamarine", pricePerCarat: 2000 }),
  "chrysophase-quartz": Object.freeze({ name: "Chrysophase (quartz)", pricePerCarat: 450 }),
  "citrine": Object.freeze({ name: "Citrine", pricePerCarat: 4000 }),
  "diamond": Object.freeze({ name: "Diamond", pricePerCarat: 15000 }),
  "emerald-green": Object.freeze({ name: "Emerald (green)", pricePerCarat: 16000 }),
  "garnet-all-other-colors": Object.freeze({ name: "Garnet (all other colors)", pricePerCarat: 1000 }),
  "garnet-black": Object.freeze({ name: "Garnet (black)", pricePerCarat: 2500 }),
  "ivory": Object.freeze({ name: "Ivory", pricePerCarat: 20 }),
  "jade": Object.freeze({ name: "Jade", pricePerCarat: 1000 }),
  "lapis-lazuli": Object.freeze({ name: "Lapis Lazuli", pricePerCarat: 5000 }),
  "malachite": Object.freeze({ name: "Malachite", pricePerCarat: 2500 }),
  "onyx": Object.freeze({ name: "Onyx", pricePerCarat: 1000 }),
  "opal-all-other-colors": Object.freeze({ name: "Opal (all other colors)", pricePerCarat: 500 }),
  "opal-black": Object.freeze({ name: "Opal (black)", pricePerCarat: 600 }),
  "opal-fire": Object.freeze({ name: "Opal (fire)", pricePerCarat: 700 }),
  "pearls-black": Object.freeze({ name: "Pearls (black)", pricePerCarat: 6000 }),
  "pearls-white": Object.freeze({ name: "Pearls (white)", pricePerCarat: 5000 }),
  "quartz-clear": Object.freeze({ name: "Quartz (clear)", pricePerCarat: 60 }),
  "quartz-rose": Object.freeze({ name: "Quartz (rose)", pricePerCarat: 150 }),
  "quartz-ruby": Object.freeze({ name: "Quartz (ruby)", pricePerCarat: 300 }),
  "quartz-smoky": Object.freeze({ name: "Quartz (smoky)", pricePerCarat: 150 }),
  "ruby-blue": Object.freeze({ name: "Ruby (blue)", pricePerCarat: 18000 }),
  "ruby-deep-red": Object.freeze({ name: "Ruby (deep red)", pricePerCarat: 19000 }),
  "sapphire-all-other-colors": Object.freeze({ name: "Sapphire (all other colors)", pricePerCarat: 16000 }),
  "sapphire-black": Object.freeze({ name: "Sapphire (black)", pricePerCarat: 20000 }),
  "star-sapphire": Object.freeze({ name: "Star Sapphire", pricePerCarat: 20000 }),
  "tiger-eye": Object.freeze({ name: "Tiger Eye", pricePerCarat: 3000 }),
  "topaz-yellow-or-brown": Object.freeze({ name: "Topaz (yellow or brown)", pricePerCarat: 200 }),
  "tourmaline-black": Object.freeze({ name: "Tourmaline (black)", pricePerCarat: 120 }),
  "turquoise": Object.freeze({ name: "Turquoise", pricePerCarat: 240 }),
  "zircon-blue": Object.freeze({ name: "Zircon (blue)", pricePerCarat: 1500 }),
  "zircon-clear": Object.freeze({ name: "Zircon (clear)", pricePerCarat: 3500 }),
  "zircon-red": Object.freeze({ name: "Zircon (red)", pricePerCarat: 2000 }),
  "zircon-yellow-brown-or-gold": Object.freeze({ name: "Zircon (yellow, brown or gold)", pricePerCarat: 300 }),
})

// Common invocations and their direct gem references.
export const RIFTS_ULTIMATE_SPELLS = [
  { level: 1, name: "Blinding Flash", ppe: 1, gemId: "quartz-clear" },
  { level: 1, name: "Cloud of Smoke", ppe: 2, gemId: "quartz-smoky" },
  { level: 1, name: "Death Trance", ppe: 1, gemId: "turquoise" },
  { level: 1, name: "Globe of Daylight", ppe: 2, gemId: "quartz-clear" },
  { level: 1, name: "Lantern Light", ppe: 1, gemId: "quartz-clear" },
  { level: 1, name: "See Aura", ppe: 6, gemId: "tiger-eye" },
  { level: 1, name: "See the Invisible", ppe: 4, gemId: "tiger-eye" },
  { level: 1, name: "Sense Evil", ppe: 2, gemId: "agate-fire" },
  { level: 1, name: "Sense Magic", ppe: 4, gemId: "agate-fire" },
  { level: 1, name: "Thunderclap", ppe: 4, gemId: "garnet-all-other-colors" },

  { level: 2, name: "Aura of Power", ppe: 4, gemId: "emerald-green" },
  { level: 2, name: "Befuddle", ppe: 6, gemId: "ruby-blue" },
  { level: 2, name: "Chameleon", ppe: 6, gemId: "turquoise" },
  { level: 2, name: "Cleanse", ppe: 6, gemId: "pearls-white" },
  { level: 2, name: "Climb", ppe: 3, gemId: "jade" },
  { level: 2, name: "Cloak of Darkness", ppe: 6, gemId: "sapphire-black" },
  { level: 2, name: "Concealment", ppe: 6, gemId: "turquoise" },
  { level: 2, name: "Detect Concealment", ppe: 6, gemId: "amber" },
  { level: 2, name: "Extinguish Fire", ppe: 4, gemId: null },
  { level: 2, name: "Fear", ppe: 5, gemId: "ruby-blue" },
  { level: 2, name: "Heavy Breathing", ppe: 5, gemId: null },
  { level: 2, name: "Levitation", ppe: 5, gemId: "pearls-black" },
  { level: 2, name: "Manipulate Objects", ppe: 2, ppeText: "2+", gemId: "opal-all-other-colors" },
  { level: 2, name: "Mystic Alarm", ppe: 5, gemId: "malachite" },
  { level: 2, name: "Shatter", ppe: 5, gemId: "quartz-ruby" },
  { level: 2, name: "Throwing Stones", ppe: 5, gemId: "opal-all-other-colors" },
  { level: 2, name: "Turn Dead", ppe: 6, gemId: "ivory" },

  { level: 3, name: "Armor of Ithan", ppe: 10, gemId: "diamond" },
  { level: 3, name: "Breathe Without Air", ppe: 5, gemId: "zircon-clear" },
  { level: 3, name: "Create Wood", ppe: 10, ppeText: "10-20", gemId: "amber" },
  { level: 3, name: "Energy Bolt", ppe: 5, gemId: "zircon-red" },
  { level: 3, name: "Fingers of the Wind", ppe: 5, gemId: "zircon-clear" },
  { level: 3, name: "Float in Air", ppe: 5, gemId: "zircon-clear" },
  { level: 3, name: "Fuel Flame", ppe: 5, gemId: "quartz-smoky" },
  { level: 3, name: "Ignite Fire", ppe: 6, gemId: "quartz-ruby" },
  { level: 3, name: "Impervious to Fire", ppe: 5, ppeText: "5; self", gemId: "quartz-smoky" },
  { level: 3, name: "Impervious to Poison", ppe: 5, gemId: "topaz-yellow-or-brown" },
  { level: 3, name: "Invisibility: Simple", ppe: 6, gemId: "emerald-green" },
  { level: 3, name: "Life Source", ppe: 2, ppeText: "2 + special", gemId: "jade" },
  { level: 3, name: "Light Healing", ppe: 6, gemId: "agate-red-orange" },
  { level: 3, name: "Light Target", ppe: 6, gemId: "quartz-clear" },
  { level: 3, name: "Magic Shield", ppe: 6, gemId: "amethyst" },
  { level: 3, name: "Mystic Fulcrum", ppe: 5, gemId: "malachite" },
  { level: 3, name: "Negate Poison/Toxin", ppe: 5, gemId: "topaz-yellow-or-brown" },
  { level: 3, name: "Orb of Cold", ppe: 6, gemId: "garnet-all-other-colors" },
  { level: 3, name: "Paralysis: Lesser", ppe: 5, gemId: "amethyst" },
  { level: 3, name: "Resist Fire", ppe: 6, ppeText: "6; others", gemId: "quartz-smoky" },
  { level: 3, name: "Telekinesis", ppe: 8, gemId: "opal-all-other-colors" },
  { level: 3, name: "Wave of Frost", ppe: 6, gemId: "garnet-all-other-colors" },

  { level: 4, name: "Astral Projection", ppe: 10, gemId: "citrine" },
  { level: 4, name: "Blind", ppe: 6, gemId: "tiger-eye" },
  { level: 4, name: "Carpet of Adhesion", ppe: 10, gemId: "amethyst" },
  { level: 4, name: "Charismatic Aura", ppe: 10, gemId: "sapphire-all-other-colors" },
  { level: 4, name: "Chromatic Protection", ppe: 10, gemId: "quartz-clear" },
  { level: 4, name: "Cure Minor Disorders", ppe: 10, gemId: "quartz-rose" },
  { level: 4, name: "Deflect", ppe: 10, gemId: "opal-all-other-colors" },
  { level: 4, name: "Electric Arc", ppe: 8, gemId: "zircon-red" },
  { level: 4, name: "Energy Field", ppe: 10, gemId: "quartz-ruby" },
  { level: 4, name: "Fire Bolt", ppe: 7, gemId: "ruby-deep-red" },
  { level: 4, name: "Fireblast", ppe: 8, gemId: "ruby-deep-red" },
  { level: 4, name: "Fist of Fury", ppe: 10, ppeText: "10 or 50", gemId: "pearls-white" },
  { level: 4, name: "Fool's Gold", ppe: 10, gemId: "zircon-yellow-brown-or-gold" },
  { level: 4, name: "Ley Line Transmission", ppe: 30, gemId: "chrysophase-quartz" },
  { level: 4, name: "Magic Net", ppe: 7, gemId: "amethyst" },
  { level: 4, name: "Multiple Image", ppe: 7, gemId: "zircon-yellow-brown-or-gold" },
  { level: 4, name: "Reflection", ppe: 7, gemId: "malachite" },
  { level: 4, name: "Repel Animals", ppe: 7, gemId: "androdite" },
  { level: 4, name: "Ricochet Strike", ppe: 12, gemId: "opal-all-other-colors" },
  { level: 4, name: "Seal", ppe: 7, gemId: "malachite" },
  { level: 4, name: "Shadow Meld", ppe: 10, gemId: "sapphire-black" },
  { level: 4, name: "Swim as a Fish", ppe: 6, gemId: "aquamarine" },
  { level: 4, name: "Trance", ppe: 10, gemId: "opal-black" },
  { level: 4, name: "Watchguard", ppe: 10, gemId: "opal-fire" },
  { level: 4, name: "Weight of Duty", ppe: 10, gemId: "sapphire-all-other-colors" },

  { level: 5, name: "Armor Bizarre", ppe: 15, gemId: "zircon-yellow-brown-or-gold" },
  { level: 5, name: "Aura of Death", ppe: 12, gemId: "ivory" },
  { level: 5, name: "Calling", ppe: 8, gemId: "sapphire-all-other-colors" },
  { level: 5, name: "Charm", ppe: 12, gemId: "ruby-blue" },
  { level: 5, name: "Circle of Flame", ppe: 10, gemId: "ruby-deep-red" },
  { level: 5, name: "Death Curse", ppe: 0, ppeText: "Special", gemId: "androdite" },
  { level: 5, name: "Distant Voice", ppe: 10, gemId: "garnet-all-other-colors" },
  { level: 5, name: "Domination", ppe: 10, gemId: "ruby-blue" },
  { level: 5, name: "Energy Disruption", ppe: 12, gemId: "quartz-ruby" },
  { level: 5, name: "Escape", ppe: 8, gemId: "jade" },
  { level: 5, name: "Eyes of Thoth", ppe: 8, gemId: "agate-fire" },
  { level: 5, name: "Featherlight", ppe: 10, gemId: "malachite" },
  { level: 5, name: "Fly", ppe: 15, gemId: "diamond" },
  { level: 5, name: "Heal Wounds", ppe: 10, gemId: "agate-red-orange" },
  { level: 5, name: "Horrific Illusion", ppe: 10, gemId: "zircon-yellow-brown-or-gold" },
  { level: 5, name: "Horror", ppe: 10, gemId: "sapphire-all-other-colors" },
  { level: 5, name: "House of Glass", ppe: 12, gemId: "topaz-yellow-or-brown" },
  { level: 5, name: "Implosion Neutralizer", ppe: 12, gemId: "tourmaline-black" },
  { level: 5, name: "Influence the Beast", ppe: 12, gemId: "alexandrite" },
  { level: 5, name: "Instill Knowledge", ppe: 15, gemId: "agate-fire" },
  { level: 5, name: "Lifeblast", ppe: 15, gemId: "jade" },
  { level: 5, name: "Mend the Broken", ppe: 10, ppeText: "10+", gemId: "amber" },
  { level: 5, name: "Mental Blast", ppe: 15, gemId: "tiger-eye" },
  { level: 5, name: "Sleep", ppe: 10, gemId: "androdite" },
  { level: 5, name: "Superhuman Endurance", ppe: 12, gemId: "pearls-black" },
  { level: 5, name: "Superhuman Speed", ppe: 10, gemId: "pearls-black" },
  { level: 5, name: "Superhuman Strength", ppe: 10, gemId: "pearls-black" },
  { level: 5, name: "Sustain", ppe: 12, gemId: "amber" },
  { level: 5, name: "Swim as a Fish - Superior", ppe: 12, gemId: "aquamarine" },

  { level: 6, name: "Apparition", ppe: 20, gemId: "zircon-yellow-brown-or-gold" },
  { level: 6, name: "Barrage", ppe: 15, gemId: "opal-all-other-colors" },
  { level: 6, name: "Call Lightning", ppe: 15, gemId: "zircon-red" },
  { level: 6, name: "Compulsion", ppe: 20, gemId: "ruby-blue" },
  { level: 6, name: "Create Water", ppe: 15, gemId: "aquamarine" },
  { level: 6, name: "Crushing Fist", ppe: 12, gemId: "diamond" },
  { level: 6, name: "Cure Illness", ppe: 15, gemId: "quartz-rose" },
  { level: 6, name: "Energize Spell", ppe: 12, ppeText: "12+", gemId: "zircon-red" },
  { level: 6, name: "Fire Ball", ppe: 10, gemId: "ruby-deep-red" },
  { level: 6, name: "Fire Blossom", ppe: 20, gemId: "quartz-smoky" },
  { level: 6, name: "Fortify Against Disease", ppe: 15, gemId: "quartz-rose" },
  { level: 6, name: "Frequency Jamming", ppe: 15, gemId: "tourmaline-black" },
  { level: 6, name: "Frostblade", ppe: 15, gemId: "garnet-all-other-colors" },
  { level: 6, name: "Ice", ppe: 15, gemId: "garnet-all-other-colors" },
  { level: 6, name: "Illusion Booster", ppe: 15, gemId: "zircon-yellow-brown-or-gold" },
  { level: 6, name: "Illusory Wall", ppe: 15, ppeText: "15 or 30", gemId: "zircon-yellow-brown-or-gold" },
  { level: 6, name: "Impervious to Energy", ppe: 20, gemId: "zircon-red" },
  { level: 6, name: "Magic Pigeon", ppe: 20, gemId: "garnet-black" },
  { level: 6, name: "Mask of Deceit", ppe: 15, gemId: "zircon-yellow-brown-or-gold" },
  { level: 6, name: "Memory Bank", ppe: 12, gemId: "agate-fire" },
  { level: 6, name: "Power Bolt", ppe: 20, gemId: "turquoise" },
  { level: 6, name: "Reduce Self", ppe: 20, gemId: "pearls-black" },
  { level: 6, name: "Sheltering Force", ppe: 20, gemId: "quartz-ruby" },
  { level: 6, name: "Targeted Deflection", ppe: 15, gemId: "opal-all-other-colors" },
  { level: 6, name: "Teleport: Lesser", ppe: 15, gemId: "lapis-lazuli" },
  { level: 6, name: "Time Slip", ppe: 20, gemId: "onyx" },
  { level: 6, name: "Tongues", ppe: 12, gemId: "agate-fire" },
  { level: 6, name: "Words of Truth", ppe: 15, gemId: "agate-fire" },

  { level: 7, name: "Agony", ppe: 20, gemId: "star-sapphire" },
  { level: 7, name: "Animate/Control Dead", ppe: 20, gemId: "ivory" },
  { level: 7, name: "Ballistic Fire", ppe: 25, gemId: "ruby-deep-red" },
  { level: 7, name: "Constrain Being", ppe: 20, gemId: "star-sapphire" },
  { level: 7, name: "Dispel Magic Barriers", ppe: 20, gemId: "lapis-lazuli" },
  { level: 7, name: "Fire Gout", ppe: 20, gemId: "ruby-deep-red" },
  { level: 7, name: "Fly as the Eagle", ppe: 25, gemId: "diamond" },
  { level: 7, name: "Globe of Silence", ppe: 20, gemId: "garnet-all-other-colors" },
  { level: 7, name: "Heal Self", ppe: 20, gemId: "agate-red-orange" },
  { level: 7, name: "Invisibility: Superior", ppe: 20, gemId: "emerald-green" },
  { level: 7, name: "Invulnerability", ppe: 25, gemId: "diamond" },
  { level: 7, name: "Ley Line Fade", ppe: 20, gemId: "emerald-green" },
  { level: 7, name: "Life Drain", ppe: 25, gemId: "ivory" },
  { level: 7, name: "Lightblade", ppe: 20, gemId: "quartz-clear" },
  { level: 7, name: "Mental Shock", ppe: 30, gemId: "tiger-eye" },
  { level: 7, name: "Metamorphosis: Animal", ppe: 25, gemId: "alexandrite" },
  { level: 7, name: "Negate Mechanics", ppe: 20, gemId: "opal-all-other-colors" },
  { level: 7, name: "Purification (Food/Water)", ppe: 20, gemId: "topaz-yellow-or-brown" },
  { level: 7, name: "Second Sight", ppe: 20, gemId: "agate-fire" },
  { level: 7, name: "See Wards", ppe: 20, gemId: "tiger-eye" },
  { level: 7, name: "Sonic Blast", ppe: 25, gemId: "garnet-all-other-colors" },
  { level: 7, name: "Spinning Blades", ppe: 20, gemId: "opal-all-other-colors" },
  { level: 7, name: "Sub-Particle Acceleration", ppe: 20, gemId: "zircon-red" },
  { level: 7, name: "Wind Rush", ppe: 20, gemId: "zircon-clear" },

  { level: 8, name: "Commune with Spirits", ppe: 25, gemId: "citrine" },
  { level: 8, name: "Exorcism", ppe: 30, gemId: "ivory" },
  { level: 8, name: "Expel Demons", ppe: 35, gemId: "opal-fire" },
  { level: 8, name: "Eyes of the Wolf", ppe: 25, gemId: "alexandrite" },
  { level: 8, name: "Fire Globe", ppe: 40, gemId: "quartz-smoky" },
  { level: 8, name: "Forcebonds", ppe: 25, gemId: "opal-fire" },
  { level: 8, name: "Greater Healing", ppe: 30, gemId: "agate-red-orange" },
  { level: 8, name: "Hallucination", ppe: 30, gemId: "sapphire-all-other-colors" },
  { level: 8, name: "Invincible Armor", ppe: 30, gemId: "diamond" },
  { level: 8, name: "Ley Line Tendril Bolts", ppe: 26, gemId: null },
  { level: 8, name: "Ley Line Time Capsule", ppe: 15, gemId: "onyx" },
  { level: 8, name: "Lifeward", ppe: 40, gemId: "jade" },
  { level: 8, name: "Lightning Arc", ppe: 30, gemId: "zircon-red" },
  { level: 8, name: "Locate", ppe: 30, gemId: "pearls-white" },
  { level: 8, name: "Luck Curse", ppe: 40, gemId: "androdite" },
  { level: 8, name: "Magical-Adrenal Rush", ppe: 45, gemId: "pearls-black" },
  { level: 8, name: "Metamorphosis: Human", ppe: 40, gemId: "alexandrite" },
  { level: 8, name: "Minor Curse", ppe: 35, gemId: "androdite" },
  { level: 8, name: "Negate Magic", ppe: 30, gemId: "lapis-lazuli" },
  { level: 8, name: "Oracle", ppe: 30, gemId: "agate-fire" },
  { level: 8, name: "Power Weapons", ppe: 35, gemId: "turquoise" },
  { level: 8, name: "Shockwave", ppe: 45, gemId: "garnet-all-other-colors" },
  { level: 8, name: "Sickness", ppe: 50, gemId: "androdite" },
  { level: 8, name: "Sorcerous Fury", ppe: 70, gemId: "zircon-red" },
  { level: 8, name: "Spoil (Water/Food)", ppe: 30, gemId: "androdite" },
  { level: 8, name: "Stone to Flesh", ppe: 30, gemId: "quartz-rose" },
  { level: 8, name: "Wall of Wind", ppe: 40, gemId: "zircon-clear" },
  { level: 8, name: "Winged Flight", ppe: 35, gemId: "garnet-black" },
  { level: 8, name: "Wisps of Confusion", ppe: 40, gemId: "ruby-blue" },
  { level: 8, name: "World Bizarre", ppe: 40, gemId: "zircon-yellow-brown-or-gold" },

  { level: 9, name: "Aura of Doom", ppe: 40, gemId: "ivory" },
  { level: 9, name: "Beat Insurmountable Odds", ppe: 70, gemId: "sapphire-all-other-colors" },
  { level: 9, name: "Create Steel", ppe: 68, gemId: "garnet-black" },
  { level: 9, name: "Curse: Phobia", ppe: 40, gemId: "androdite" },
  { level: 9, name: "D-Step", ppe: 50, gemId: "tourmaline-black" },
  { level: 9, name: "Desiccate the Supernatural", ppe: 50, gemId: "opal-fire" },
  { level: 9, name: "Dragon Fire", ppe: 40, gemId: "ruby-deep-red" },
  { level: 9, name: "Familiar Link", ppe: 55, gemId: "jade" },
  { level: 9, name: "Illusion Manipulation", ppe: 25, ppeText: "25-60", gemId: "zircon-yellow-brown-or-gold" },
  { level: 9, name: "Ley Line Phantom", ppe: 40, gemId: "emerald-green" },
  { level: 9, name: "Ley Line Time Flux", ppe: 80, gemId: "onyx" },
  { level: 9, name: "Metamorphosis: Insect", ppe: 60, gemId: "alexandrite" },
  { level: 9, name: "Mute", ppe: 50, gemId: "amethyst" },
  { level: 9, name: "Phantom Mount", ppe: 45, gemId: "pearls-white" },
  { level: 9, name: "Protection Circle: Simple", ppe: 45, gemId: "sapphire-all-other-colors" },
  { level: 9, name: "Purge Self", ppe: 70, gemId: "agate-red-orange" },
  { level: 9, name: "Realm of Chaos", ppe: 70, gemId: "pearls-white" },
  { level: 9, name: "Speed of the Snail", ppe: 50, gemId: "star-sapphire" },
  { level: 9, name: "Summon and Control Canine", ppe: 50, gemId: "citrine" },
  { level: 9, name: "Swords to Snakes", ppe: 50, gemId: "pearls-white" },
  { level: 9, name: "Tame Beast", ppe: 60, gemId: "alexandrite" },
  { level: 9, name: "Transferal", ppe: 50, gemId: "opal-black" },
  { level: 9, name: "Wall of Defense", ppe: 55, gemId: "diamond" },
  { level: 9, name: "Water to Wine", ppe: 40, gemId: "aquamarine" },

  { level: 10, name: "Armorbane", ppe: 100, gemId: "opal-all-other-colors" },
  { level: 10, name: "Banishment", ppe: 65, gemId: "opal-fire" },
  { level: 10, name: "Control/Enslave Entity", ppe: 80, gemId: "star-sapphire" },
  { level: 10, name: "Deathword", ppe: 70, gemId: "star-sapphire" },
  { level: 10, name: "Enemy Mind", ppe: 100, gemId: "opal-black" },
  { level: 10, name: "Giant", ppe: 80, gemId: "pearls-black" },
  { level: 10, name: "Havoc", ppe: 70, gemId: "amethyst" },
  { level: 10, name: "Illusory Forest", ppe: 45, ppeText: "45-90", gemId: "zircon-yellow-brown-or-gold" },
  { level: 10, name: "Ley Line Ghost", ppe: 80, gemId: "emerald-green" },
  { level: 10, name: "Magic Warrior", ppe: 60, gemId: "pearls-white" },
  { level: 10, name: "Metamorphosis: Superior", ppe: 100, gemId: "alexandrite" },
  { level: 10, name: "Meteor", ppe: 75, gemId: "onyx" },
  { level: 10, name: "Mystic Portal", ppe: 60, gemId: "onyx" },
  { level: 10, name: "Plane Skip", ppe: 65, gemId: "onyx" },
  { level: 10, name: "Purge Other", ppe: 100, gemId: "agate-red-orange" },
  { level: 10, name: "Reality Flux", ppe: 75, gemId: "opal-fire" },
  { level: 10, name: "Restore Limb", ppe: 80, gemId: "agate-red-orange" },
  { level: 10, name: "Speed Weapon", ppe: 100, gemId: "turquoise" },
  { level: 10, name: "Summon Greater Familiar", ppe: 80, gemId: "chrysophase-quartz" },
  { level: 10, name: "Summon Shadow Beast", ppe: 140, gemId: "chrysophase-quartz" },
  { level: 10, name: "Summon/Control Rodents", ppe: 70, gemId: "citrine" },
  { level: 10, name: "Super-Healing", ppe: 70, gemId: "agate-red-orange" },
  { level: 10, name: "Wall of Not", ppe: 70, gemId: "emerald-green" },
  { level: 10, name: "Wards", ppe: 90, gemId: "diamond" },
  { level: 10, name: "Warped Space", ppe: 90, gemId: "onyx" },

  { level: 11, name: "Anti-Magic Cloud", ppe: 140, gemId: "lapis-lazuli" },
  { level: 11, name: "Astral Hole", ppe: 120, gemId: "citrine" },
  { level: 11, name: "Bottomless Pit", ppe: 100, gemId: "tourmaline-black" },
  { level: 11, name: "Create Magic Scroll", ppe: 100, gemId: "garnet-black" },
  { level: 11, name: "Create Mummy", ppe: 160, gemId: "ivory" },
  { level: 11, name: "Curse of the World Bizarre", ppe: 100, gemId: "androdite" },
  { level: 11, name: "Disharmonize", ppe: 150, gemId: "opal-black" },
  { level: 11, name: "Energy Sphere", ppe: 120, gemId: "quartz-ruby" },
  { level: 11, name: "Firequake", ppe: 160, gemId: "quartz-smoky" },
  { level: 11, name: "Id Alter Ego", ppe: 130, gemId: "opal-black" },
  { level: 11, name: "Illusory Terrain", ppe: 55, ppeText: "55-120", gemId: "zircon-yellow-brown-or-gold" },
  { level: 11, name: "Ley Line Storm Defense", ppe: 180, gemId: "tourmaline-black" },
  { level: 11, name: "Mindshatter", ppe: 130, gemId: "tiger-eye" },
  { level: 11, name: "Re-Open Gateway", ppe: 180, gemId: "onyx" },
  { level: 11, name: "Remove Curse", ppe: 140, gemId: "quartz-rose" },
  { level: 11, name: "Rift Teleportation", ppe: 200, gemId: "onyx" },
  { level: 11, name: "Rift to Limbo", ppe: 160, gemId: "onyx" },
  { level: 11, name: "See in Magic Darkness", ppe: 125, gemId: "tiger-eye" },
  { level: 11, name: "Summon & Control Animals", ppe: 125, gemId: "citrine" },
  { level: 11, name: "Summon Fog", ppe: 140, gemId: "zircon-blue" },

  { level: 12, name: "Amulet", ppe: 290, ppeText: "290+", gemId: "malachite" },
  { level: 12, name: "Calm Storms", ppe: 200, gemId: "zircon-blue" },
  { level: 12, name: "Create Zombie", ppe: 250, gemId: "ivory" },
  { level: 12, name: "Ensorcel", ppe: 400, gemId: "star-sapphire" },
  { level: 12, name: "Heavy Air", ppe: 200, gemId: "zircon-clear" },
  { level: 12, name: "Ironwood", ppe: 50, ppeText: "50+", gemId: "amber" },
  { level: 12, name: "Metamorphosis: Mist", ppe: 250, gemId: "alexandrite" },
  { level: 12, name: "Null Sphere", ppe: 220, gemId: "sapphire-black" },
  { level: 12, name: "Soultwist", ppe: 170, gemId: "star-sapphire" },
  { level: 12, name: "Summon & Control Entity", ppe: 250, gemId: "citrine" },
  { level: 12, name: "Summon & Control Rain", ppe: 200, gemId: "zircon-blue" },
  { level: 12, name: "Summon Ley Line Storm", ppe: 500, gemId: "chrysophase-quartz" },
  { level: 12, name: "Swallowing Rift", ppe: 300, gemId: "onyx" },
  { level: 12, name: "Time Hole", ppe: 210, gemId: "onyx" },
  { level: 12, name: "Wall of the Weird", ppe: 180, gemId: "jade" },

  { level: 13, name: "Collapse", ppe: 70, ppeText: "70-400", gemId: "malachite" },
  { level: 13, name: "Create Golem", ppe: 700, ppeText: "700 or 1000", gemId: "garnet-black" },
  { level: 13, name: "Protection Circle: Superior", ppe: 300, gemId: "sapphire-all-other-colors" },
  { level: 13, name: "Restore Life", ppe: 275, gemId: "agate-red-orange" },
  { level: 13, name: "Sanctum", ppe: 390, gemId: "lapis-lazuli" },
  { level: 13, name: "Shadow Wall", ppe: 400, gemId: "sapphire-black" },
  { level: 13, name: "Summon & Control Storm", ppe: 300, gemId: "zircon-blue" },
  { level: 13, name: "Summon Lesser Being", ppe: 425, gemId: "chrysophase-quartz" },
  { level: 13, name: "Swap Places", ppe: 300, gemId: "onyx" },
  { level: 13, name: "Talisman", ppe: 500, gemId: "malachite" },

  { level: 14, name: "Annihilate", ppe: 600, gemId: "lapis-lazuli" },
  { level: 14, name: "Close Rift", ppe: 200, ppeText: "200+", gemId: "onyx" },
  { level: 14, name: "Id Barrier", ppe: 600, gemId: "opal-black" },
  { level: 14, name: "Impenetrable Wall of Force", ppe: 600, gemId: "diamond" },
  { level: 14, name: "Restoration", ppe: 750, gemId: "agate-red-orange" },
  { level: 14, name: "Resurrection", ppe: 650, gemId: "agate-red-orange" },
  { level: 14, name: "Rift Triangular Defense System", ppe: 840, gemId: "onyx" },
  { level: 14, name: "Summon & Control Sea Serpents", ppe: 350, gemId: "aquamarine" },

  { level: 15, name: "Circle of Travel", ppe: 600, gemId: "onyx" },
  { level: 15, name: "Dimensional Portal", ppe: 1000, gemId: "onyx" },
  { level: 15, name: "Dimensional Teleport", ppe: 800, gemId: "onyx" },
  { level: 15, name: "Enchant Weapon", ppe: 400, ppeText: "400 to 1000+", gemId: "garnet-black" },
  { level: 15, name: "Ley Line Restoration", ppe: 800, gemId: "agate-red-orange" },
  { level: 15, name: "Ley Line Shutdown", ppe: 3000, gemId: "tourmaline-black" },
  { level: 15, name: "Summon Ally", ppe: 600, gemId: "sapphire-all-other-colors" },
  { level: 15, name: "Teleport: Superior", ppe: 600, gemId: "lapis-lazuli" },
  { level: 15, name: "Transformation", ppe: 2000, gemId: "androdite" },
  { level: 15, name: "Void", ppe: 700, gemId: "lapis-lazuli" },
].sort((a, b) => a.name.localeCompare(b.name))
